// GENERATED FILE - DO NOT EDIT.
// Source: protocol/hud-espnow-v1.json
// Regenerate: node scripts/gen-hud-protocol.mjs
#pragma once

#define HUD_PKT_TELEMETRY_SIZE 14
#define HUD_PKT_LOCATION_SIZE 17
#define HUD_PKT_HEARTBEAT_SIZE 8
#define HUD_PKT_ROUTE_HEADER_SIZE 10
#define HUD_ROUTE_CHUNK_BYTES 200
#define HUD_PKT_ROUTE_SIZE 210
#define HUD_HEARTBEAT_MS 3000
#define HUD_HEARTBEAT_TIMEOUT_MS 10000
#define HUD_ROUTE_CHUNK_MS 60
#define HUD_ROUTE_MAX_CYCLES 4
#define HUD_SEGMENT_NONE 255
#define HUD_SEGMENTS_SHOWN 3
#define HUD_LINK_CHANNEL 1
#define HUD_SEND_TELEMETRY_MS 1000
#define HUD_SEND_LOCATION_MS 5000
#define HUD_LOCATION_ZOOM 1
#define HUD_FISHEYE 220
#define HUD_FISHEYE_MIN 100
#define HUD_FISHEYE_MAX 500
#define HUD_TOT_SCALE 10
#define HUD_MODE_STATS 0
#define HUD_MODE_MAP 1
#define HUD_ANGLE_MIN -359
#define HUD_ANGLE_MAX 359
#define HUD_STATS_ABOVE_KMH 30.0f

#define HUD_WIRE_PROTO "szusownik/hud-espnow-v1"
#define HUD_PKT_TELEMETRY 'S'
#define HUD_PKT_LOCATION 'L'
#define HUD_PKT_HEARTBEAT 'H'
#define HUD_PKT_ROUTE 'R'
